version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mkdocs-material
    versions:
    - 6.2.6
    - 6.2.7
    - 6.2.8
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 7.1.0
    - 7.1.1
    - 7.1.2
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mkdocstrings
    versions:
    - 0.14.0
