__title__ = "Phillip"
__description__ = "An event-driven for osu! feeds."
__url__ = "https://github.com/rorre/Phillip"
__version__ = "0.1.0"
__author__ = "Rendy Arya Kemal"
__author_email__ = "rendyarya22@gmail.com"
__license__ = "LGPLv3"
